Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
       
  config.vm.define "JenkinsServer" do |jenkinssrv|
    jenkinssrv.vm.box = "ubuntu/jammy64"
    jenkinssrv.vm.hostname = "jenkinssrv"
    jenkinssrv.vm.network "private_network", ip: "192.168.35.36"
    jenkinssrv.vm.network "public_network"
    jenkinssrv.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4" # Set number of CPUs to 4
    end
    jenkinssrv.vm.provision "shell", path: "userdata/jenkins.install.sh"
  end

  config.vm.define "JenkinsAgent" do |jenkinsagent|
    jenkinsagent.vm.box = "ubuntu/jammy64"
    jenkinsagent.vm.hostname = "jenkinsagent"
    jenkinsagent.vm.network "private_network", ip: "192.168.35.38"
    jenkinsagent.vm.network "public_network"
    jenkinsagent.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2" # Set number of CPUs to 2
    end
    jenkinsagent.vm.provision "shell", path: "userdata/jenkins.install.sh"
  end

end
