Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    # config.vm.synced_folder ".", "/vagrant"
    db01.vbguest.installer_options = { allow_kernel_upgrade: true }
    db01.vm.network "private_network", ip: "192.168.56.55"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "1200"
   end
  end

### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vbguest.installer_options = { allow_kernel_upgrade: true }
    mc01.vm.network "private_network", ip: "192.168.56.54"
    mc01.vm.provider "virtualbox" do |vb|
     vb.memory = "1200"
   end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vbguest.installer_options = { allow_kernel_upgrade: true }
    rmq01.vm.network "private_network", ip: "192.168.56.53"
    rmq01.vm.provider "virtualbox" do |vb|
     vb.memory = "1200"
   end
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vbguest.installer_options = { allow_kernel_upgrade: true }
    app01.vm.network "private_network", ip: "192.168.56.52"
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "1600"
   end
  end
   
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.51"
    web01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1600"
   end
  end

end
