Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01e82af4e524a0aa3
      Tags:
        - Key: "Name"
          Value: "MyFirstInstance"