Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
       
  config.vm.define "microsrv" do |microsrv|
    microsrv.vm.box = "ubuntu/jammy64"
    microsrv.vm.hostname = "microsrv"
    microsrv.vm.network "private_network", ip: "192.168.35.36"
    microsrv.vm.network "public_network"
    microsrv.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "6" # Set number of CPUs to 6
    end
    microsrv.vm.provision "shell", path: "userdata/docker.sh"
  end
end
