apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd
        tier: frontend
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
